/* eslint-disable @typescript-eslint/no-unsafe-call */
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
    seed: 'pnpm exec ts-node prisma/seed.ts',
  },
  datasource: {
    url: `postgresql://postgres:password123@119.59.102.57:5432/streaming_db?schema=public`,
    // url: process.env['DATABASE_URL'],
  },
});
