services:
  app:
    build:
      context: ./back-steaming
      dockerfile: Dockerfile
    container_name: nest-chat-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./back-steaming/.env
    networks:
      - streaming-network

  front:
    build:
      context: ./front-steaming
      dockerfile: Dockerfile
    container_name: next-frontend-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./front-steaming/.env
    networks:
      - streaming-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: streaming_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streaming-network

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: unless-stopped
    command: --config /etc/livekit.yaml --bind 0.0.0.0
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "50000-50020:50000-50020/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    networks:
      - streaming-network

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: media-server
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8889:8889/udp"
    environment:
      - MTX_WEBRTCADDITIONALHOSTS=127.0.0.1
    networks:
      - streaming-network

volumes:
  postgres_data:

networks:
  streaming-network:
    driver: bridge
