name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project folder to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/steaming-project"

      - name: Run Docker Compose on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/steaming-project

            # 1. สร้างโฟลเดอร์ back-staeaming ให้มั่นใจว่ามีอยู่จริง และสร้างไฟล์ .env ไว้ข้างใน
            mkdir -p back-staeaming
            echo "${{ secrets.PRODUCTION_ENV }}" > back-staeaming/.env

            # 2. รัน Docker Compose เพื่อ Build และอัปเดตระบบ
            docker compose down
            docker compose up -d --build

            # 3. ล้าง Docker image เก่าที่ไม่ได้ใช้งาน เพื่อประหยัดพื้นที่บน Server
            docker image prune -f